### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by SecretLoved** [CRAZYShimakaze/zhenxun_extensive_plugin#35]
## 概述
成语接龙只能到第二步就报错结束

## 系统环境
Ubuntu 20
## 重现步骤
接成语接龙没反应

## Bug行为
：成语接龙 仁至义尽 1
：@暖杯巧克力  已发起对局，请挑战者在None秒内发送'接'+以jin开头的成语，赌注1金币！(之前说过的不能再说)
：接尽力而为
## 附件
附上图片或日志，日志请用格式：
 
![image](https://user-images.githubusercontent.com/73172198/188173914-7e20339b-b9b5-4312-b42d-9a26b08eddb6.png)
![image](https://user-images.githubusercontent.com/73172198/188173962-934686b1-5610-4578-8a37-58ac9182f4f9.png)

> ```
> 日志内容
> ```

**Comment by CRAZYShimakaze** [comment]
确认一下plugins2config.yaml里面有以下代码：
````
idiom_salon:
# 成语接龙
  DATI_TIME:
    value: 40
    name:
    help: 答题时间
    default_value: 40
    level_module:
````
确认一下config.yaml里面有以下代码：
````
idiom_salon:
  # 成语接龙
  # DATI_TIME: 答题时间
  DATI_TIME: 40
````
如果没有请添加，添加后再无法运行应该是真寻本体的问题了。
